spring:
  application:
    name: ordering-service
#  profiles:
#    active: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        impl.uuid_binary_compatibility: true # PostgreSQL UUID 매핑 최적화용 (남겨두는 것 권장)
  http:
    client:
      connect-timeout: 3s  # 연결 지연 타임아웃 (3초)
      read-timeout: 5s     # 응답 지연 타임아웃 (5초)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

springdoc:
  api-docs:
    path: /api/api-spec
    enabled: true
  swagger-ui:
    path: /api/api-docs
    enabled: true
  override-with-generic-response: false
  use-fqn: true

jwt:
  issuer: ordering
  secret: ${JWT_SECRET}
  access-token:
    validity-seconds: ${JWT_ACCESS_EXPIRATION}
  refresh-token:
    validity-seconds: ${JWT_REFRESH_EXPIRATION}

time:
  zone-id: ${TIME_ZONE_ID:Asia/Seoul}

resetpassword:
  validity-seconds: 600 # 10분

gemini:
  url: ${GEMINI_URL}
  api-key: ${GEMINI_API_KEY}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace